name = "Anlhord"
description = "Programmer diary"
license = "MIT"
tags = ["blog", "programmer"]

[author]
    name = "spf13"
    homepage = "http://spf13.com"

# If Porting existing theme
[original]
    author =  "arnp"
    repo = "http://www.github.com/arnp/herring-cove"
